COMPILE=gcc -Wall -I./include -g -D_DEFAULT_SOURCE

program:
	$(COMPILE) -c src/hw/sim.c -o sim.o
	$(COMPILE) -c src/core/program.c -o program.o
	$(COMPILE) -c src/core/sensors.c -o sensors.o
	$(COMPILE) -c src/sim/main.c -o main.o
	$(COMPILE) -o main main.o program.o sensors.o sim.o -lm

clean:
	rm -f *.o main
