CFLAGS=-Wall -I./include -g -D_DEFAULT_SOURCE
LDFLAGS=-lm

SRC := src
OBJ := obj/sim

SOURCES := $(wildcard $(SRC)/core/*.c) $(wildcard $(SRC)/sim/*.c) $(SRC)/hw/sim.c
OBJECTS := $(subst .c,.o,$(SOURCES))
OBJECTS := $(subst $(SRC)/,$(OBJ)/,$(OBJECTS))
OBJDIRS := $(dir $(OBJECTS))

$(OBJ)/%.o: $(SRC)/%.c
	@mkdir -p $(OBJ)/$(OBJDIRS)
	$(CC) $(CFLAGS) -c $< -o $@

sim: $(OBJECTS)
	$(CC) $^ -o $@ $(LDFLAGS)

clean:
	rm -rf $(OBJ) sim

all: sim
